//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOH.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOH.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acreedores y proveedores.
        /// </summary>
        public static string AcreedoresYProveedores {
            get {
                return ResourceManager.GetString("AcreedoresYProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de sitios.
        /// </summary>
        public static string AdministracionDeSitios {
            get {
                return ResourceManager.GetString("AdministracionDeSitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agencias.
        /// </summary>
        public static string Agencias {
            get {
                return ResourceManager.GetString("Agencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Ajustes {
            get {
                return ResourceManager.GetString("Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Áreas de interés.
        /// </summary>
        public static string AreasDeInteres {
            get {
                return ResourceManager.GetString("AreasDeInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda de caras.
        /// </summary>
        public static string BusquedaDeCaras {
            get {
                return ResourceManager.GetString("BusquedaDeCaras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caras.
        /// </summary>
        public static string Caras {
            get {
                return ResourceManager.GetString("Caras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caras bonificadas.
        /// </summary>
        public static string CarasBonificadas {
            get {
                return ResourceManager.GetString("CarasBonificadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargos.
        /// </summary>
        public static string Cargos {
            get {
                return ResourceManager.GetString("Cargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías de caras.
        /// </summary>
        public static string CategoriaDeCaras {
            get {
                return ResourceManager.GetString("CategoriaDeCaras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías de sitios.
        /// </summary>
        public static string CategoriasDeSitios {
            get {
                return ResourceManager.GetString("CategoriasDeSitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones.
        /// </summary>
        public static string Configuraciones {
            get {
                return ResourceManager.GetString("Configuraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones reportes PPT.
        /// </summary>
        public static string ConfiguracionesReportesPPT {
            get {
                return ResourceManager.GetString("ConfiguracionesReportesPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ConfirmarContrasena {
            get {
                return ResourceManager.GetString("ConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas.
        /// </summary>
        public static string Consultas {
            get {
                return ResourceManager.GetString("Consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratación de sitios.
        /// </summary>
        public static string ContratacionDeSitios {
            get {
                return ResourceManager.GetString("ContratacionDeSitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos a clientes.
        /// </summary>
        public static string ContratosAClientes {
            get {
                return ResourceManager.GetString("ContratosAClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos por sitio.
        /// </summary>
        public static string ContratosPorSitio {
            get {
                return ResourceManager.GetString("ContratosPorSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos por sitios por vencer.
        /// </summary>
        public static string ContratosPorSitiosPorVencer {
            get {
                return ResourceManager.GetString("ContratosPorSitiosPorVencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos por vendedor por mes.
        /// </summary>
        public static string ContratosPorVendedorPorMes {
            get {
                return ResourceManager.GetString("ContratosPorVendedorPorMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos vigentes por cliente por mes.
        /// </summary>
        public static string ContratosVigentesPorClientePorMes {
            get {
                return ResourceManager.GetString("ContratosVigentesPorClientePorMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos y O.P.s en proceso.
        /// </summary>
        public static string ContratosYOpsEnProceso {
            get {
                return ResourceManager.GetString("ContratosYOpsEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de instalaciones por proveedor.
        /// </summary>
        public static string ControlDeInstalacionesPorProveedor {
            get {
                return ResourceManager.GetString("ControlDeInstalacionesPorProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizaciones.
        /// </summary>
        public static string Cotizaciones {
            get {
                return ResourceManager.GetString("Cotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamentos.
        /// </summary>
        public static string Departamentos {
            get {
                return ResourceManager.GetString("Departamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad de caras.
        /// </summary>
        public static string DisponibilidadDeCaras {
            get {
                return ResourceManager.GetString("DisponibilidadDeCaras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad y cotizaciones.
        /// </summary>
        public static string DisponibilidadYCotizaciones {
            get {
                return ResourceManager.GetString("DisponibilidadYCotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos para contratos.
        /// </summary>
        public static string DocumentosParaContratos {
            get {
                return ResourceManager.GetString("DocumentosParaContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutivos de venta.
        /// </summary>
        public static string EjecutivosDeVenta {
            get {
                return ResourceManager.GetString("EjecutivosDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        public static string Empleados {
            get {
                return ResourceManager.GetString("Empleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuestas.
        /// </summary>
        public static string Encuestas {
            get {
                return ResourceManager.GetString("Encuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación por cara.
        /// </summary>
        public static string FacturacionPorCara {
            get {
                return ResourceManager.GetString("FacturacionPorCara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos por sitio.
        /// </summary>
        public static string GastosPorSitio {
            get {
                return ResourceManager.GetString("GastosPorSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maestros.
        /// </summary>
        public static string Maestros {
            get {
                return ResourceManager.GetString("Maestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de sitios.
        /// </summary>
        public static string MantenimientoDeSitios {
            get {
                return ResourceManager.GetString("MantenimientoDeSitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        public static string Mantenimientos {
            get {
                return ResourceManager.GetString("Mantenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapas e imágenes.
        /// </summary>
        public static string MapasEImagenes {
            get {
                return ResourceManager.GetString("MapasEImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcas y rubros.
        /// </summary>
        public static string MarcasYRubros {
            get {
                return ResourceManager.GetString("MarcasYRubros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipios.
        /// </summary>
        public static string Municipios {
            get {
                return ResourceManager.GetString("Municipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string Notificaciones {
            get {
                return ResourceManager.GetString("Notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He olvidado mi contraseña.
        /// </summary>
        public static string OlvidasteContrasena {
            get {
                return ResourceManager.GetString("OlvidasteContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones.
        /// </summary>
        public static string Operaciones {
            get {
                return ResourceManager.GetString("Operaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Órdenes de producción.
        /// </summary>
        public static string OrdenesDeProduccion {
            get {
                return ResourceManager.GetString("OrdenesDeProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origenes de interés.
        /// </summary>
        public static string OrigenesDeInteres {
            get {
                return ResourceManager.GetString("OrigenesDeInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos de ingreso.
        /// </summary>
        public static string PermisosDeIngreso {
            get {
                return ResourceManager.GetString("PermisosDeIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promociones.
        /// </summary>
        public static string Promociones {
            get {
                return ResourceManager.GetString("Promociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prospectos de sitio.
        /// </summary>
        public static string ProspectosDeSitios {
            get {
                return ResourceManager.GetString("ProspectosDeSitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerdame.
        /// </summary>
        public static string Recuerdame {
            get {
                return ResourceManager.GetString("Recuerdame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rentabilidad por caras por zonas.
        /// </summary>
        public static string RentabilidadPorCarasPorZonas {
            get {
                return ResourceManager.GetString("RentabilidadPorCarasPorZonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rentabilidad por sitios.
        /// </summary>
        public static string RentabilidadPorSitios {
            get {
                return ResourceManager.GetString("RentabilidadPorSitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservaciones.
        /// </summary>
        public static string Reservaciones {
            get {
                return ResourceManager.GetString("Reservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitios.
        /// </summary>
        public static string Sitios {
            get {
                return ResourceManager.GetString("Sitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifas de proveedores.
        /// </summary>
        public static string TarifasDeProveedores {
            get {
                return ResourceManager.GetString("TarifasDeProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de estructuras.
        /// </summary>
        public static string TipoDeEstructuras {
            get {
                return ResourceManager.GetString("TipoDeEstructuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos configuraciones reportes PPT.
        /// </summary>
        public static string TiposConfiguracionesReportesPPT {
            get {
                return ResourceManager.GetString("TiposConfiguracionesReportesPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de cara.
        /// </summary>
        public static string TiposDeCara {
            get {
                return ResourceManager.GetString("TiposDeCara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de estado.
        /// </summary>
        public static string TiposDeEstado {
            get {
                return ResourceManager.GetString("TiposDeEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de imágenes.
        /// </summary>
        public static string TiposDeImagenes {
            get {
                return ResourceManager.GetString("TiposDeImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de materiales.
        /// </summary>
        public static string TiposDeMateriales {
            get {
                return ResourceManager.GetString("TiposDeMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de permiso.
        /// </summary>
        public static string TiposDePermiso {
            get {
                return ResourceManager.GetString("TiposDePermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de precio.
        /// </summary>
        public static string TiposDePrecio {
            get {
                return ResourceManager.GetString("TiposDePrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de proveedores.
        /// </summary>
        public static string TiposDeProveedores {
            get {
                return ResourceManager.GetString("TiposDeProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de referencias comerciales.
        /// </summary>
        public static string TiposDeReferenciasComerciales {
            get {
                return ResourceManager.GetString("TiposDeReferenciasComerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de restricciones comerciales.
        /// </summary>
        public static string TiposDeRestriccionesComerciales {
            get {
                return ResourceManager.GetString("TiposDeRestriccionesComerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de seguro.
        /// </summary>
        public static string TiposDeSeguro {
            get {
                return ResourceManager.GetString("TiposDeSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de trabajos OP.
        /// </summary>
        public static string TiposDeTrabajosOp {
            get {
                return ResourceManager.GetString("TiposDeTrabajosOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos y categorías.
        /// </summary>
        public static string TiposYCatergorias {
            get {
                return ResourceManager.GetString("TiposYCatergorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilidad por instalación.
        /// </summary>
        public static string UtilidadPorInstalacion {
            get {
                return ResourceManager.GetString("UtilidadPorInstalacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vallas.
        /// </summary>
        public static string Vallas {
            get {
                return ResourceManager.GetString("Vallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencimiento de contratos por cara.
        /// </summary>
        public static string VencimientoDeContratosPorCara {
            get {
                return ResourceManager.GetString("VencimientoDeContratosPorCara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas.
        /// </summary>
        public static string Zonas {
            get {
                return ResourceManager.GetString("Zonas", resourceCulture);
            }
        }
    }
}
